# -*- coding: utf-8 -*-
"""Part 4 — Brain & Mood, Energy & Endurance, Immunity."""
from data1 import FRIDGE, FRIDGE_LIGHT
from data3 import NOHUMAN, RESEARCH

C4 = [
dict(slug="semax", name="Semax", cat="Brain & Mood",
  what="A nasal spray peptide developed in Russia and used there after strokes. It raises the brain's own growth factors.",
  cls="ACTH(4-10) analogue", half="Minutes", route="Up the nose",
  cadence="daily", days=[1,1,1,1,1,1,1], perWeek=7,
  cadNote="Daily, split across the day, because it clears within minutes.",
  when="Morning and early afternoon", food="Either",
  timeNote="It's stimulating, so a late dose can keep you awake. Most protocols stop by mid-afternoon.",
  ev="regional", evNote="A registered medicine in Russia for stroke recovery and cognitive problems. Not approved in the US, Europe, the UK or Australia.",
  protocol=[("In Russia","Nasal, split through the day","Doses depend on what it's being used for."),
            ("Elsewhere","Not approved","No approved dose outside its home country."),
            ("Route","Up the nose","Going through the nose gets it to the brain — that's the registered route.")],
  benefits=["Raises BDNF and NGF, the brain's own repair and growth signals.",
            "Registered for stroke recovery where it's approved.",
            "Studied for attention, focus and protecting brain cells.",
            "Calms anxiety without making you drowsy."],
  sizes=[(10,"mg",2100000)], dose=0.3, unit="mg",
  storage=FRIDGE_LIGHT, cautions=["Approved in Russia only — unapproved almost everywhere else.",
    "Limited long-term safety data outside its home market."]),

dict(slug="selank", name="Selank", cat="Brain & Mood",
  what="Semax's calmer sibling, also Russian and also a nasal spray. Built for anxiety rather than focus, without sedation or dependence.",
  cls="Tuftsin analogue", half="Minutes", route="Up the nose",
  cadence="daily", days=[1,1,1,1,1,1,1], perWeek=7,
  cadNote="Daily, split across the day. Very short-acting.",
  when="Morning and afternoon", food="Either",
  timeNote="Not sedating, so timing is flexible. Split doses keep the effect level through the day.",
  ev="regional", evNote="Registered in Russia for anxiety. Not approved in Western countries.",
  protocol=[("In Russia","Nasal, split through the day","Registered for anxiety disorders."),
            ("Elsewhere","Not approved","No approved dose outside Russia."),
            ("Compared with","Benzodiazepines","Studied as a non-sedating, non-addictive alternative.")],
  benefits=["Eases anxiety without sedation or the fog that comes with it.",
            "No dependence or withdrawal, unlike standard anxiety medicines.",
            "Affects serotonin and BDNF signalling.",
            "Often paired with Semax — one calms, one sharpens."],
  sizes=[(10,"mg",2100000)], dose=0.3, unit="mg",
  storage=FRIDGE_LIGHT, cautions=["Approved in Russia only.","Long-term data is thin outside its home market."]),

dict(slug="selank-semax", name="Selank + Semax", cat="Brain & Mood",
  what="Both Russian nootropic peptides in one pen — one for calm, one for focus. They're usually run together.",
  cls="Tuftsin analogue + ACTH(4-10) analogue", half="Minutes", route="Up the nose",
  cadence="daily", days=[1,1,1,1,1,1,1], perWeek=7,
  cadNote="Daily, split across the day. Both parts are very short-acting.",
  when="Morning and early afternoon", food="Either",
  timeNote="The Semax half is stimulating, so keep the last dose well before bed.",
  ev="regional", evNote="Both are registered in Russia individually. The combination is not separately approved anywhere.",
  protocol=[("Each part","Registered in Russia","Semax for stroke and cognition, Selank for anxiety."),
            ("The pair","Not separately approved","The combination itself has no approval."),
            ("Why together","They balance each other","One sharpens focus, the other takes the edge off.")],
  benefits=["Focus and calm together, which most single compounds can't do.",
            "Both raise BDNF, the brain's growth signal.",
            "One injection instead of two."],
  sizes=[(20,"mg",3900000)], dose=0.6, unit="mg",
  storage=FRIDGE_LIGHT, cautions=["Unapproved outside Russia.","The combination hasn't been trialled as a pair."]),

dict(slug="cerebrolysin", name="Cerebrolysin", cat="Brain & Mood",
  what="A mix of small peptides made from pig brain protein. It's an old medicine, used in parts of Europe and Asia after strokes and in dementia.",
  cls="Porcine brain-derived peptide preparation", half="Varies by fraction", route="Injected — into muscle or a vein",
  cadence="cycle", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="Given as a course — typically weekdays for several weeks, then a break, rather than continuously.",
  when="Morning", food="Either",
  timeNote="Given in the morning in clinical use. Courses are repeated a few times a year rather than run non-stop.",
  ev="regional", evNote="An approved medicine in Russia, China, Austria and a number of other countries for stroke and dementia. Not approved in the US or most of Western Europe.",
  protocol=[("Clinical course","Daily for 10–20 days","Then a break before repeating. Amounts depend on the condition."),
            ("Route","Into muscle or a drip","Larger amounts are given as a drip in hospital."),
            ("Status","Approved in some countries","Availability depends entirely on where you are.")],
  benefits=["Acts like the brain's own growth factors.",
            "Approved for stroke recovery and dementia where it's registered.",
            "One of the few things here with decades of clinical use behind it.",
            "Studied for traumatic brain injury too."],
  sizes=[(80,"mg",2700000)], dose=5, unit="mg",
  storage=FRIDGE, cautions=["Made from animal brain tissue — allergic reactions are possible.",
    "Not approved in the US or most of Western Europe.","Should be given by someone medically trained."]),

dict(slug="dihexa", name="Dihexa", cat="Brain & Mood",
  what="A small molecule built to boost a growth factor in the brain, aimed at building new connections between brain cells. Very early-stage.",
  cls="Angiotensin IV analogue / HGF potentiator", half="Long for its size", route="By mouth or under the skin in studies",
  cadence="daily", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="Daily in animal protocols. No human schedule exists.",
  when="Morning", food="Either",
  timeNote="Morning dosing in study protocols. It crosses into the brain easily, which is unusual for its type.",
  ev="preclinical", evNote="Animal data only. No human trials at all, and no established dose.",
  protocol=[NOHUMAN, ("Studied in","Rat memory models","The headline claims come from rodent studies."),
            ("Status","Not approved", RESEARCH)],
  benefits=["Boosts hepatocyte growth factor signalling, which drives new connections between brain cells.",
            "Crosses into the brain far better than most peptides.",
            "Studied for memory in animal models of dementia."],
  sizes=[(10,"mg",3500000)], dose=1, unit="mg",
  storage=FRIDGE, cautions=["No human data whatsoever — this is one of the least-tested things in the catalogue.",
    "Anything that drives new tissue growth carries theoretical cancer concerns.","Research use only."]),

dict(slug="pinealon", name="Pinealon", cat="Brain & Mood",
  what="A three amino acid peptide from the Russian bioregulator family, aimed at brain cells. Meant to be used in short courses, not continuously.",
  cls="Short peptide bioregulator (Glu-Asp-Arg)", half="Minutes", route="Under the skin",
  cadence="cycle", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="A 10 to 20 day course, then a long break. That course-and-gap pattern is standard for this whole family.",
  when="Morning", food="Either",
  timeNote="Morning dosing in the source literature, run as short courses a few times a year.",
  ev="regional", evNote="Sold as a supplement in Russia. The research is largely from one group and hasn't been independently repeated. No approved medical use.",
  protocol=[("Course pattern","10–20 days, then a break","The standard pattern for this family."),
            ("Human dose","Not established","No regulator has set one."),
            ("Status","A supplement in Russia","Not an approved medicine anywhere.")],
  benefits=["Studied for memory and mental sharpness in ageing.",
            "Thought to work at the level of gene expression in brain cells.",
            "Protects brain cells from oxygen stress in animal work."],
  sizes=[(20,"mg",3300000)], dose=1, unit="mg",
  storage=FRIDGE, cautions=["The evidence comes largely from a single research group.","Not an approved medicine."]),

dict(slug="adamax", name="Adamax", cat="Brain & Mood",
  what="A modified version of Semax, built to last longer and hit harder. Newer and much less studied than the original.",
  cls="Modified ACTH(4-10) / Semax analogue", half="Longer than Semax", route="Up the nose or under the skin",
  cadence="daily", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="Daily, usually as a short course. Longer-lasting than Semax, so fewer doses a day.",
  when="Morning", food="Either",
  timeNote="Stimulating, like Semax — morning dosing avoids sleep problems.",
  ev="preclinical", evNote="Very little published data even compared with Semax. No approved use and no set dose.",
  protocol=[NOHUMAN, ("Related to","Semax","A modified version built for a longer effect."),
            ("Status","Not approved", RESEARCH)],
  benefits=["Longer-acting than Semax, so fewer doses.",
            "Raises BDNF, like the rest of this family.",
            "Studied for focus and memory."],
  sizes=[(10,"mg",2800000)], dose=0.3, unit="mg",
  storage=FRIDGE_LIGHT, cautions=["Much less studied than Semax, which is itself barely studied outside Russia.",
    "Research use only."]),

]

C5 = [
dict(slug="mots-c", name="MOTS-c", cat="Energy & Endurance",
  what="A peptide your mitochondria make — the parts of your cells that produce energy. It acts like a signal that you've been exercising.",
  cls="Mitochondrial-derived peptide", half="Short — minutes to hours", route="Under the skin",
  cadence="cycle", days=[1,0,1,0,1,0,0], perWeek=3,
  cadNote="Every other day in study protocols rather than daily. No human schedule is established.",
  when="Morning", food="Either",
  timeNote="Morning dosing is conventional in the metabolic literature, though it isn't established.",
  ev="preclinical", evNote="Mostly animal and observational work. No approved use and no set human dose.",
  protocol=[NOHUMAN, ("Study pattern","Alternate days","Animal metabolic studies dose intermittently rather than continuously."),
            ("Status","Not approved", RESEARCH)],
  benefits=["Switches on AMPK — the same energy sensor exercise activates.",
            "Improves insulin sensitivity and glucose handling in animal models.",
            "Studied for exercise capacity and mitochondrial function.",
            "Levels fall with age, which is why it turns up in longevity research."],
  sizes=[(10,"mg",2200000),(40,"mg",3800000)], dose=5, unit="mg",
  storage=FRIDGE_LIGHT, cautions=["No human safety data.","Research use only."]),

dict(slug="5-amino-1mq", name="5-Amino-1MQ", cat="Energy & Endurance",
  what="A small molecule that blocks an enzyme fat cells use to slow their own metabolism. Blocking it lets fat cells burn more.",
  cls="NNMT inhibitor", half="Short", route="By mouth or under the skin",
  cadence="daily", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="Daily in study protocols, usually as a course of several weeks.",
  when="Morning", food="Either",
  timeNote="Morning dosing in most protocols. Often taken by mouth rather than injected.",
  ev="preclinical", evNote="Animal data only. No human trials, no approved use, no set dose.",
  protocol=[NOHUMAN, ("Studied in","Obese mouse models","The fat-loss findings come from rodents."),
            ("Status","Not approved", RESEARCH)],
  benefits=["Raises NAD+ inside fat cells, which lifts their metabolic rate.",
            "Reduced fat mass in animal models without cutting food intake.",
            "Studied for muscle preservation alongside fat loss."],
  sizes=[(50,"mg",2900000)], dose=5, unit="mg",
  storage=FRIDGE, cautions=["No human trials at all.","Research use only."]),

dict(slug="aicar", name="AICAR", cat="Energy & Endurance",
  what="A compound that switches on the same cellular energy sensor exercise does. It got famous as 'exercise in a pill' — which oversells it.",
  cls="AMPK activator", half="Short", route="Under the skin or as a drip",
  cadence="daily", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="Daily in study protocols. The amounts used in animal studies are large, which is a practical problem.",
  when="Before training or in the morning", food="Either",
  timeNote="Timed around exercise in study protocols, since it works on the same pathway training does.",
  ev="trial", evNote="Studied in humans for heart protection during surgery. Not approved for metabolic or performance use, and banned in sport.",
  protocol=[("Trial use","As a drip, in heart surgery","That's where the human data comes from."),
            ("Performance use","Not established","No trial has set a dose for this."),
            ("Status","Banned in sport","On the WADA list. " + RESEARCH)],
  benefits=["Activates AMPK, the master energy switch that exercise turns on.",
            "Increased endurance in the well-known mouse studies.",
            "Studied for glucose uptake and fat burning."],
  sizes=[(50,"mg",2700000)], dose=5, unit="mg",
  storage=FRIDGE, cautions=["Banned in sport.",
    "The doses used in animal studies are far larger than is practical in people.","Not approved for this use."]),

dict(slug="slu-pp-332", name="SLU-PP-332", cat="Energy & Endurance",
  what="A newer compound that mimics some effects of endurance training by switching on a gene regulator in muscle.",
  cls="ERR-alpha agonist", half="Short", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="Daily in animal protocols. No human schedule exists.",
  when="Before training or in the morning", food="Either",
  timeNote="Study protocols time it around exercise, matching the pathway it acts on.",
  ev="preclinical", evNote="Animal data only, and quite recent. No human trials and no set dose.",
  protocol=[NOHUMAN, ("Studied in","Mouse endurance models","Improved running endurance and fat burning in mice."),
            ("Status","Not approved","Very new — even the animal data is thin. " + RESEARCH)],
  benefits=["Switches on the genes that endurance training normally activates.",
            "Increased running endurance and fat burning in mice.",
            "Doesn't act through stimulants, so it doesn't raise heart rate the way those do."],
  sizes=[(5,"mg",2400000)], dose=0.5, unit="mg",
  storage=FRIDGE, cautions=["Extremely new — even the animal evidence is limited.",
    "No human data at all.","Research use only."]),

dict(slug="l-carnitine", name="L-Carnitine (Injectable)", cat="Energy & Endurance",
  what="A nutrient that ferries fat into the mitochondria to be burned. Your body makes it and you get it from red meat; the injectable form is a real medicine for people who are deficient.",
  cls="Levocarnitine", half="About 15 hours", route="Into muscle or a vein",
  cadence="daily", days=[1,1,1,1,1,1,1], perWeek=7,
  cadNote="Daily or several times a week, depending on what it's for.",
  when="Before training or in the morning", food="Either",
  timeNote="Often timed before exercise, on the logic that it's moving fat into the furnace.",
  ev="label", evNote="Approved as Carnitor for carnitine deficiency. Using it for fat loss or performance is off-label and much less supported.",
  protocol=[("Approved use","For carnitine deficiency","Doses are set by a doctor for the deficiency being treated."),
            ("Fat loss use","Off-label","The evidence for fat loss in people who aren't deficient is weak."),
            ("Status","Prescription medicine","Approved, but for a specific and uncommon condition.")],
  benefits=["Essential for moving fat into cells to be burned.",
            "An approved medicine with a long safety record.",
            "Injection bypasses the poor absorption of the oral form.",
            "Studied for fatigue and exercise recovery."],
  sizes=[(5000,"mg",2700000)], dose=500, unit="mg",
  storage="Room temperature is fine for this one, but the fridge does no harm. Keep it out of direct light.",
  cautions=["The fat-loss evidence in healthy people is weak — don't expect much.",
    "Can cause a fishy body odour at higher amounts.","Prescription medicine in most countries."]),

dict(slug="lipo-b", name="LC216 Lipo-B (Injectable)", cat="Energy & Endurance",
  what="A 'lipotropic' blend — B vitamins plus amino acids that help the liver process fat. Common in weight-loss clinics.",
  cls="Lipotropic injection (methionine, inositol, choline, B vitamins)", half="Varies by ingredient", route="Into muscle",
  cadence="weekly", days=[1,0,0,0,0,0,0], perWeek=1,
  cadNote="Usually once or twice a week in clinic practice.",
  when="Morning", food="Either",
  timeNote="Morning injections are the norm because the B12 component can be mildly energising.",
  ev="preclinical", evNote="A compounded clinic blend, not an approved medicine. Good evidence that it causes weight loss is lacking.",
  protocol=[("Clinic practice","Weekly or twice weekly","How it's typically given, though this isn't from trials."),
            ("Evidence","Weak","No solid trial shows it drives weight loss on its own."),
            ("Status","A compounded blend","Not an approved product.")],
  benefits=["Supplies B12 and B-complex, which genuinely matter for energy metabolism.",
            "The amino acids involved do support how the liver handles fat.",
            "Generally well tolerated."],
  sizes=[(10,"mL",2700000)], dose=1, unit="mL",
  storage=FRIDGE_LIGHT, cautions=["The weight-loss evidence is weak — treat the claims sceptically.",
    "Not an approved medicine."]),

dict(slug="fat-blaster", name="LC526 Fat Blaster (Injectable)", cat="Energy & Endurance",
  what="Another lipotropic clinic blend, along the same lines as Lipo-B with a slightly different mix.",
  cls="Lipotropic injection blend", half="Varies by ingredient", route="Into muscle",
  cadence="weekly", days=[1,0,0,0,0,0,0], perWeek=1,
  cadNote="Once or twice a week in clinic practice.",
  when="Morning", food="Either",
  timeNote="Morning, for the same reason as Lipo-B — the B12 can be mildly energising.",
  ev="preclinical", evNote="A compounded clinic blend, not an approved medicine, without trial evidence behind the weight-loss claim.",
  protocol=[("Clinic practice","Weekly or twice weekly","Typical practice, not a trial-based schedule."),
            ("Evidence","Weak","As with other lipotropic blends."),
            ("Status","A compounded blend","Not approved.")],
  benefits=["B vitamins and amino acids that support fat metabolism.",
            "Usually used as a support alongside diet changes, not instead of them.",
            "Generally well tolerated."],
  sizes=[(10,"mL",2700000)], dose=1, unit="mL",
  storage=FRIDGE_LIGHT, cautions=["Little evidence it drives weight loss by itself.","Not an approved medicine."]),
]

C6 = [
dict(slug="thymosin-alpha-1", name="Thymosin Alpha-1", cat="Immunity",
  what="A peptide your thymus makes to train immune cells. It's a real approved medicine in a number of countries, mostly for hepatitis B.",
  cls="Immune-modulating peptide", half="About 2 hours", route="Under the skin",
  cadence="weekly", days=[1,0,0,1,0,0,0], perWeek=2,
  cadNote="Twice a week, spaced three or four days apart — the approved pattern.",
  when="Any time of day", food="Either",
  timeNote="Timing within the day isn't critical. Spacing the two weekly doses evenly is what matters.",
  ev="regional", evNote="Approved as Zadaxin in around 30 countries for hepatitis B and as a vaccine booster. Not approved in the US.",
  protocol=[("Approved dose","1.6 mg twice a week","Under the skin, in the hepatitis B regimen."),
            ("Course length","Months, not weeks","Approved courses run long."),
            ("US status","Not approved","Approval varies by country.")],
  benefits=["Helps T-cells mature and work properly — the core of how it acts.",
            "An approved treatment for chronic hepatitis B where it's registered.",
            "Studied as a vaccine booster and in sepsis and cancer care.",
            "One of the few immune peptides with genuine regulatory approval."],
  sizes=[(10,"mg",3300000)], dose=1.6, unit="mg",
  storage=FRIDGE, cautions=["It modulates the immune system — relevant if you have an autoimmune condition or a transplant.",
    "Approval varies by country; check where you are."]),

dict(slug="thymalin", name="Thymalin", cat="Immunity",
  what="An older Russian thymus extract used to support immune function in the elderly. A mix of peptides rather than one defined molecule.",
  cls="Thymus peptide extract", half="Varies", route="Into muscle",
  cadence="cycle", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="Given as a 5 to 10 day course, then a long break — the standard Russian bioregulator pattern.",
  when="Morning", food="Either",
  timeNote="Given as short courses a couple of times a year rather than continuously.",
  ev="regional", evNote="Registered in Russia. The long-term human data comes largely from one research group and hasn't been independently repeated.",
  protocol=[("Course pattern","5–10 days, then a break","The standard pattern for this family."),
            ("Russian data","Long-term follow-up studies","Reported reduced mortality in elderly cohorts — not independently replicated."),
            ("Status","Registered in Russia only","Not approved in Western countries.")],
  benefits=["Supports thymus function, which declines steeply with age.",
            "Studied for immune restoration in older people.",
            "Long follow-up data exists, unusually for this category."],
  sizes=[(10,"mg",2500000)], dose=1, unit="mg",
  storage=FRIDGE, cautions=["An animal-derived extract rather than a defined single molecule.",
    "Key evidence comes from a single research group.","Not approved outside Russia."]),
]
