# -*- coding: utf-8 -*-
"""Part 5 — 07 Sexual Health, 08 Longevity, 09 Bioregulators."""
from data1 import FRIDGE, FRIDGE_LIGHT
from data3 import NOHUMAN, RESEARCH

C7 = [
dict(slug="pt-141", name="PT-141 (Bremelanotide)", cat="Sexual Health",
  what="A shot for low sexual desire that works in the brain rather than on blood flow — a different route entirely from Viagra-type drugs.",
  cls="Melanocortin receptor agonist", half="About 2.7 hours", route="Under the skin",
  cadence="as-needed", days=[0,0,0,0,0,0,0], perWeek=2,
  cadNote="Taken when you need it, not on a schedule.",
  when="At least 45 minutes before", food="Either — a heavy meal slows it down",
  timeNote="The limit that matters isn't the hour but the ceiling: one dose in 24 hours, and no more than eight in a month.",
  ev="label", evNote="Approved by the FDA as Vyleesi for low sexual desire in premenopausal women. The doses below are the official ones.",
  protocol=[("Official dose","1.75 mg when needed","A single injection into the belly or thigh."),
            ("Timing","45 minutes or more before","The lead time on the label."),
            ("Limit","1 per day, 8 per month","The official ceiling — this is the binding constraint.")],
  benefits=["Works on desire in the brain, not on blood flow — a genuinely different mechanism.",
            "Taken when needed rather than every day.",
            "Studied in both women (where it's approved) and men."],
  sizes=[(10,"mg",2300000)], dose=1.75, unit="mg",
  storage=FRIDGE_LIGHT, cautions=["Nausea is the most common side effect on the label.",
    "It briefly raises blood pressure — not for uncontrolled high blood pressure or heart disease.",
    "Repeated use can cause patches of darker skin."]),

dict(slug="hcg", name="HCG", cat="Sexual Health",
  what="A hormone that tells the testicles or ovaries to get to work. In men it acts like the body's own signal to make testosterone.",
  cls="Human chorionic gonadotropin", half="About 24–36 hours", route="Under the skin or into muscle",
  cadence="weekly", days=[1,0,1,0,1,0,0], perWeek=3,
  cadNote="Usually two or three times a week, spaced evenly — it lasts more than a day.",
  when="Any time of day", food="Either",
  timeNote="Timing within the day isn't important. Even spacing across the week is.",
  ev="label", evNote="An approved medicine worldwide, for low testosterone caused by pituitary problems in men and for fertility treatment in women.",
  protocol=[("Men, low testosterone","Doses set by a doctor","Typically a few thousand IU a couple of times a week, adjusted from blood tests."),
            ("Fertility use","A single trigger dose","Used to trigger ovulation, timed to a monitored cycle."),
            ("Status","Prescription only","Requires blood monitoring.")],
  benefits=["Keeps the testicles working, which is why it's used alongside testosterone therapy.",
            "Preserves fertility where testosterone alone shuts it down.",
            "An approved medicine with decades of use.",
            "Triggers ovulation in fertility treatment."],
  sizes=[(10000,"IU",2700000)], dose=500, unit="IU",
  storage="Fridge, 2–8 °C, once mixed. Keep out of the light. Don't freeze.",
  cautions=["Prescription medicine — it needs blood test monitoring.",
    "Can raise oestrogen in men, causing breast tissue growth.","Banned in sport."]),

dict(slug="hmg", name="HMG", cat="Sexual Health",
  what="A fertility hormone preparation containing both FSH and LH. In men it's used alongside HCG when sperm production needs restarting.",
  cls="Human menopausal gonadotropin (menotropins)", half="Varies by component", route="Under the skin or into muscle",
  cadence="weekly", days=[1,0,1,0,1,0,0], perWeek=3,
  cadNote="Two or three times a week in male fertility protocols; daily in monitored IVF cycles.",
  when="Any time of day", food="Either",
  timeNote="In fertility treatment the timing is dictated by cycle monitoring, not by convenience.",
  ev="label", evNote="Approved as Menopur and similar products for fertility treatment. Male use alongside HCG is well established in specialist practice.",
  protocol=[("Fertility use","Set by a specialist","Doses are adjusted from scans and blood tests during a cycle."),
            ("Male use","With HCG","Used to restart sperm production; doses set by a specialist."),
            ("Status","Prescription only","Requires monitoring.")],
  benefits=["Contains both hormones the gonads need, not just one.",
            "An approved fertility medicine with a long record.",
            "Used with HCG to restore sperm production after testosterone use."],
  sizes=[(75,"IU",2400000)], dose=75, unit="IU",
  storage="Fridge once mixed. Out of the light. Don't freeze.",
  cautions=["Prescription medicine requiring specialist monitoring.",
    "Overstimulation is a real risk in women without monitoring."]),

dict(slug="kisspeptin", name="Kisspeptin", cat="Sexual Health",
  what="The hormone that starts the whole reproductive chain — it sits above the others and tells the brain to begin the cascade. It's also being studied for desire.",
  cls="Kisspeptin-10", half="Minutes", route="Under the skin",
  cadence="as-needed", days=[0,0,0,0,0,0,0], perWeek=2,
  cadNote="Very short-acting, so protocols use it episodically rather than on a schedule.",
  when="Before activity, or in the morning", food="Either",
  timeNote="It breaks down within minutes, so any effect is close to the time you take it.",
  ev="trial", evNote="Studied in real human trials at Imperial College London for desire and reproductive function. Not approved.",
  protocol=[("Trial use","Given as a drip in studies","Human trials used controlled infusions, not self-injection."),
            ("Human dose","Not established for self-use","No trial has set a dose outside a research setting."),
            ("Status","Not approved", RESEARCH)],
  benefits=["Sits at the top of the reproductive hormone chain, above LH and FSH.",
            "Trial data showed effects on brain activity linked to attraction and desire.",
            "Studied for fertility as well as libido."],
  sizes=[(10,"mg",2900000)], dose=0.5, unit="mg",
  storage=FRIDGE, cautions=["Human data comes from controlled infusions, not self-injection.","Not approved."]),

dict(slug="oxytocin", name="Oxytocin Acetate", cat="Sexual Health",
  what="The bonding hormone — released during touch, closeness and childbirth. The injectable form is an approved hospital medicine.",
  cls="Oxytocin", half="About 3–5 minutes", route="Under the skin, up the nose, or a drip in hospital",
  cadence="as-needed", days=[0,0,0,0,0,0,0], perWeek=3,
  cadNote="Episodic. It breaks down within minutes, so it's used close to when you want the effect.",
  when="Shortly before", food="Either",
  timeNote="Very short-acting — nasal use in social and bonding studies is timed 30 to 45 minutes ahead.",
  ev="label", evNote="Approved as an injection in hospital for labour. Using it for bonding, anxiety or intimacy is off-label and much less established.",
  protocol=[("Approved use","Labour, as a hospital drip","Carefully controlled and monitored."),
            ("Social or nasal use","Not established","Research studies use nasal sprays; no dose is approved for this."),
            ("Status","Prescription medicine","The approved use is obstetric.")],
  benefits=["Central to bonding, trust and social connection.",
            "An approved medicine with a long hospital record.",
            "Studied for social anxiety and closeness in relationships."],
  sizes=[(10,"mg",2700000)], dose=0.5, unit="mg",
  storage=FRIDGE, cautions=["The approved use is childbirth, under monitoring — that's a serious medicine.",
    "Too much can cause water retention and low sodium.","Social use is not an approved use."]),

dict(slug="melanotan-2", name="Melanotan II", cat="Sexual Health",
  what="A peptide that darkens skin by triggering pigment cells, and also raises libido as a side effect. Widely sold, and the most safety-flagged item in this catalogue.",
  cls="Melanocortin receptor agonist", half="About 1–2 hours", route="Under the skin",
  cadence="cycle", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="A loading phase, then occasional top-ups. Not intended for continuous use.",
  when="Evening", food="Either",
  timeNote="Evening dosing is common because nausea and flushing are the usual early effects, and sleeping through them is easier.",
  ev="preclinical", evNote="Not approved anywhere. Health authorities in several countries have issued warnings about it, and it is not tested for safety in people.",
  protocol=[("Human dose","Not established","Not approved anywhere; no dose has been set."),
            ("Known effects","Tanning, nausea, libido","All reported, but from unregulated use, not trials."),
            ("Warnings issued","By several regulators","The UK, Australia and others have warned against it.")],
  benefits=["Darkens skin without sun exposure — the reason most people use it.",
            "Raises libido, which is how the related approved drug PT-141 was discovered.",
            "Reduces appetite in some users."],
  sizes=[(10,"mg",1900000)], dose=0.25, unit="mg",
  storage=FRIDGE_LIGHT,
  cautions=["It darkens existing moles and can make new ones — which makes spotting skin cancer harder. This is the serious one.",
    "Nausea and flushing are very common at the start.",
    "Several health authorities have formally warned against it. Not approved anywhere."]),
]

C8 = [
dict(slug="nad-plus", name="NAD+", cat="Longevity",
  what="A molecule every cell needs to make energy and repair DNA. Levels drop steeply with age, which is why it's the centrepiece of a lot of longevity work.",
  cls="Nicotinamide adenine dinucleotide", half="Short — cleared quickly", route="Under the skin or as a slow drip",
  cadence="weekly", days=[1,0,0,0,0,0,0], perWeek=1,
  cadNote="Weekly or a few times a month for drips; smaller injections can be more frequent.",
  when="Morning", food="Either",
  timeNote="Morning is usual because it can be mildly energising. Drips must go slowly — fast infusion causes chest tightness and nausea.",
  ev="trial", evNote="Precursors like NR and NMN have real human trials; direct NAD+ injection and infusion have far less evidence and no approval.",
  protocol=[("IV clinic practice","Given very slowly","Speed is the issue — fast infusion causes unpleasant effects."),
            ("Injection dose","Not established","No trial has set one for injected NAD+."),
            ("Better evidence","For NR and NMN by mouth","The precursors have the stronger human trial data.")],
  benefits=["Central to how every cell makes energy.",
            "Needed by the sirtuin repair enzymes tied to ageing.",
            "Levels fall sharply with age — the basis of the whole interest.",
            "Studied for fatigue, brain fog and recovery."],
  sizes=[(500,"mg",2300000),(1000,"mg",3700000)], dose=100, unit="mg",
  storage=FRIDGE_LIGHT, cautions=["Infusing it fast causes chest tightness, flushing and nausea — it has to go slowly.",
    "Injected NAD+ has much weaker evidence than the oral precursors.","Not an approved medicine."]),

dict(slug="epithalon", name="Epithalon", cat="Longevity",
  what="A four amino acid peptide from Russian ageing research, best known for claims about telomeres — the caps on your chromosomes that shorten as you age.",
  cls="Synthetic tetrapeptide (pineal-derived)", half="Minutes", route="Under the skin",
  cadence="cycle", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="A short course of 10 to 20 days, then months off. Not taken continuously.",
  when="Evening", food="Either",
  timeNote="Evening dosing in the source literature, tied to the pineal gland's melatonin rhythm.",
  ev="preclinical", evNote="The human data comes from a small body of Russian work that hasn't been independently repeated. No approved use and no established dose.",
  protocol=[("Human dose","Not established","No regulator has set one, and the source studies haven't been replicated."),
            ("Course pattern","Short course, long gap","The literature uses defined courses a few times a year."),
            ("Status","Not approved", RESEARCH)],
  benefits=["The telomerase findings from cell studies are what drew longevity interest.",
            "Studied for melatonin rhythm and sleep quality.",
            "Antioxidant effects in animal ageing models."],
  sizes=[(50,"mg",3100000)], dose=5, unit="mg",
  storage=FRIDGE_LIGHT, cautions=["The evidence is thin and comes largely from one source.","Research use only."]),

dict(slug="dsip", name="DSIP", cat="Longevity",
  what="A peptide named for its effect on deep sleep in early animal work. The name promises more than the evidence delivers.",
  cls="Delta sleep-inducing peptide", half="Minutes", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="Used before bed when used at all, as a short course rather than nightly forever.",
  when="Before bed", food="Either",
  timeNote="Taken shortly before sleep. It clears fast, so it's aimed at falling asleep rather than staying asleep.",
  ev="preclinical", evNote="Animal work and a few small old human studies. Results have been inconsistent, and there's no approved use or set dose.",
  protocol=[NOHUMAN, ("Named for","Deep sleep in animals","The name comes from early rabbit studies."),
            ("Human results","Inconsistent","Small old studies gave mixed results. " + RESEARCH)],
  benefits=["Studied for deep sleep, which is the restorative stage.",
            "Doesn't work like a sedative, so it doesn't leave grogginess.",
            "Also studied for stress hormones and pain."],
  sizes=[(5,"mg",1900000),(10,"mg",2300000)], dose=0.1, unit="mg",
  storage=FRIDGE, cautions=["Human results have been inconsistent — don't count on it.","Research use only."]),

dict(slug="ss-31", name="SS-31", cat="Longevity",
  what="A peptide that targets the inner membrane of mitochondria to protect how cells make energy. It has real late-stage trials behind it, unusually for this category.",
  cls="Elamipretide / mitochondria-targeted peptide", half="A few hours", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,1,1], perWeek=7,
  cadNote="Daily in the clinical trials.",
  when="Morning", food="Either",
  timeNote="Trials used consistent daily dosing; time of day wasn't the variable.",
  ev="trial", evNote="Has completed phase 2 and 3 trials as elamipretide for mitochondrial disease and heart failure. Not approved, but the human data is real.",
  protocol=[("Trial dose","40 mg daily","The dose used in the mitochondrial disease trials."),
            ("Trial results","Mixed","Some endpoints were met, others were not — approval has not followed."),
            ("Status","Not approved","Genuine trial data exists, which sets it apart in this category.")],
  benefits=["Targets the specific membrane where cells make energy.",
            "Has real phase 3 human trial data behind it.",
            "Studied for mitochondrial disease, heart failure and eye disease.",
            "Reduces oxidative damage inside mitochondria."],
  sizes=[(50,"mg",4000000)], dose=5, unit="mg",
  storage=FRIDGE, cautions=["Trial results were mixed and approval hasn't followed.","Not an approved medicine."]),

dict(slug="humanin", name="Humanin", cat="Longevity",
  what="Another peptide made by mitochondria, this one protecting cells from dying under stress. Levels drop with age.",
  cls="Mitochondrial-derived peptide", half="Short", route="Under the skin",
  cadence="cycle", days=[1,0,1,0,1,0,0], perWeek=3,
  cadNote="Intermittent in study protocols. No human schedule exists.",
  when="Morning", food="Either",
  timeNote="Morning dosing by convention in the metabolic literature, not from any established protocol.",
  ev="preclinical", evNote="Animal and cell studies, plus observational human data linking higher levels to longer life. No trials, no approved use, no set dose.",
  protocol=[NOHUMAN, ("Observational data","Higher levels, longer life","Seen in centenarian studies — association, not proof."),
            ("Status","Not approved", RESEARCH)],
  benefits=["Protects cells from dying under stress.",
            "Found at higher levels in people who live exceptionally long.",
            "Studied for Alzheimer's and heart protection in animal models.",
            "Improves insulin sensitivity in animal work."],
  sizes=[(10,"mg",4000000)], dose=1, unit="mg",
  storage=FRIDGE, cautions=["No human trials.","Research use only."]),

dict(slug="foxo4-dri", name="FOXO4-DRI", cat="Longevity",
  what="A peptide designed to kill senescent cells — worn-out cells that stop dividing but won't die, and leak inflammation into the tissue around them.",
  cls="FOXO4-p53 interaction inhibitor (senolytic)", half="Short", route="Under the skin",
  cadence="cycle", days=[1,0,1,0,1,0,0], perWeek=3,
  cadNote="Given in short bursts — a few doses, then a long gap. Senolytics are used as pulses, not continuously.",
  when="Morning", food="Either",
  timeNote="The pulsed pattern is deliberate: you're clearing a population of cells, not maintaining a level.",
  ev="preclinical", evNote="One well-known mouse study and lab work. No human trials at all, no approved use, no established dose.",
  protocol=[NOHUMAN, ("The famous study","Aged mice, 2017","Restored fur, kidney function and fitness in old mice."),
            ("Status","Not approved","One striking animal study is not human evidence. " + RESEARCH)],
  benefits=["Targets senescent cells, thought to drive a lot of age-related inflammation.",
            "The mouse study showed genuinely striking reversal of ageing markers.",
            "Pulsed dosing means far less exposure than a daily compound."],
  sizes=[(10,"mg",4600000)], dose=1, unit="mg",
  storage=FRIDGE, cautions=["No human data at all — the evidence is one mouse study.",
    "It works by killing cells, which is not a gentle mechanism.","Research use only."]),

dict(slug="glutathione", name="Glutathione", cat="Longevity",
  what="Your body's main built-in antioxidant. The injectable form is used mostly for skin brightening, which is not an approved use anywhere.",
  cls="Tripeptide antioxidant (glutamate-cysteine-glycine)", half="Short in blood", route="Under the skin or as a drip",
  cadence="weekly", days=[1,0,0,1,0,0,0], perWeek=2,
  cadNote="Once or twice a week in clinic practice.",
  when="Any time of day", food="Either",
  timeNote="Clinic practice varies. There's no established schedule because there's no approved use.",
  ev="trial", evNote="Oral and inhaled forms have human studies. Injectable glutathione for skin lightening is not approved, and the FDA has warned about compounded injectable versions.",
  protocol=[("Skin lightening","Not approved","The most common use has no approval and thin evidence."),
            ("Clinic practice","Weekly IV, commonly","Practice varies widely; no trial has set a dose."),
            ("Safety warnings","Issued by regulators","The Philippines FDA and others have warned about IV use.")],
  benefits=["The body's main antioxidant, involved in clearing toxins from the liver.",
            "Supports how the liver processes waste.",
            "Popular for skin brightening, though the evidence is weak."],
  sizes=[(1500,"mg",2300000)], dose=300, unit="mg",
  storage=FRIDGE_LIGHT, cautions=["Regulators have warned specifically about injectable glutathione for skin lightening.",
    "Serious reactions including Stevens-Johnson syndrome have been reported with IV use.",
    "Not an approved use."]),
]

# --- 09 Bioregulators: one family, differing by target organ ---
BIOREG = [
 ("bronchogen","Bronchogen","the lungs and airways","Studied for chronic bronchitis and airway inflammation."),
 ("cardiogen","Cardiogen","the heart muscle","Studied for heart muscle recovery and blood vessel health."),
 ("cartalax","Cartalax","cartilage and joints","Studied for cartilage repair and joint inflammation."),
 ("chonluten","Chonluten","the lung lining","Studied for the lung lining and the gut lining together."),
 ("cortagen","Cortagen","the brain cortex","Studied for nerve repair and brain recovery after injury."),
 ("crystagen","Crystagen","the immune system","Studied for immune balance and thymus function."),
 ("livagen","Livagen","the liver","Studied for liver function and blood cell health."),
 ("ovagen","Ovagen","the liver and gut","Studied for liver protection and gut lining repair."),
 ("pancragen","Pancragen","the pancreas","Studied for pancreas function and blood sugar handling."),
 ("prostamax","Prostamax","the prostate","Studied for prostate function and urinary symptoms in older men."),
 ("testagen","Testagen","the testicles","Studied for testosterone production and reproductive function."),
 ("vesugen","Vesugen","blood vessel walls","Studied for blood vessel lining health and circulation."),
]

C9 = [dict(slug=slug, name=name, cat="Bioregulators",
  what="A very short peptide from the Russian bioregulator family, aimed at " + organ + ". The idea is that each one signals its target tissue to repair itself.",
  cls="Short peptide bioregulator (Khavinson peptide)", half="Minutes", route="Under the skin",
  cadence="cycle", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="A 10 to 20 day course, then months off. Every peptide in this family is used in courses, never continuously.",
  when="Morning", food="Either",
  timeNote="Morning dosing in the source literature. The course-then-break pattern matters far more than the time of day.",
  ev="regional", evNote="Sold as supplements in Russia. Nearly all the research comes from one group in St Petersburg and has not been independently repeated. No approved medical use.",
  protocol=[("Course pattern","10–20 days, then a break","The standard pattern across this whole family."),
            ("Human dose","Not established","No regulator has set one."),
            ("Status","A supplement in Russia","Not an approved medicine anywhere else.")],
  benefits=[study, "Thought to act on gene expression in its target tissue.",
            "Used in short courses, so total exposure stays low.",
            "Part of a family with decades of use in Russia, though little of it independently verified."],
  sizes=[(20,"mg",3300000)], dose=1, unit="mg",
  storage=FRIDGE,
  cautions=["Almost all the evidence comes from a single research group and hasn't been replicated.",
            "Sold as a supplement, not an approved medicine."])
  for slug, name, organ, study in BIOREG]
