# -*- coding: utf-8 -*-
"""Part 3 — 03 Healing & Repair, 04 Brain & Mood."""
from data1 import FRIDGE, FRIDGE_LIGHT

NOHUMAN = ("Human dose","Not set","No completed human trials have set a dose. Any number presented as an established dose isn't backed by published evidence.")
RESEARCH = "Sold for laboratory research only, not as a medicine."

C3 = [
dict(slug="bpc-157", name="BPC-157", cat="Healing & Repair",
  what="A short peptide copied from a protein found in stomach juice. It's the best-known repair peptide, studied mostly for tendons, ligaments and gut lining.",
  cls="Synthetic pentadecapeptide", half="Short — minutes", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,1,1], perWeek=7,
  cadNote="Daily, often split morning and evening, because it clears the body fast. No human schedule has been established.",
  when="Morning and evening", food="Either",
  timeNote="Split dosing shows up in animal studies because it doesn't last long. Some protocols inject near the injured area, though the evidence for that is thin.",
  ev="preclinical", evNote="No completed human trials. There is no established human dose, and any figure quoted as one isn't supported by published evidence.",
  protocol=[NOHUMAN, ("Animal studies","Micrograms per kg","Animal work shows effects across a wide range. Those numbers don't translate straight to people."),
            ("Legal status","Not approved","On the FDA's excluded-substances list. " + RESEARCH)],
  benefits=["Tendon, ligament and muscle healing — the most repeated finding in animal work.",
            "Protects the gut lining in ulcer and colitis models.",
            "Encourages new blood vessel growth, which is how it's thought to speed repair.",
            "Studied for protecting the stomach against damage from anti-inflammatory painkillers."],
  sizes=[(10,"mg",1600000)], dose=0.25, unit="mg",
  storage=FRIDGE, cautions=["No long-term human safety data exists.",
    "It grows new blood vessels, which is the point — and also the reason for caution if any cancer is present.",
    "Research use only, not a medicine."]),

dict(slug="tb-500", name="TB-500", cat="Healing & Repair",
  what="A fragment of a protein your body already makes that helps cells move to where damage is. Usually paired with BPC-157.",
  cls="Thymosin beta-4 fragment", half="Longer than BPC-157", route="Under the skin",
  cadence="weekly", days=[1,0,0,1,0,0,0], perWeek=2,
  cadNote="Twice a week to start, spaced three or four days apart, then less often. That's the animal-study pattern — no human schedule exists.",
  when="Any time of day", food="Either",
  timeNote="It lasts longer than BPC-157, so timing within the day matters little. Spacing across the week is what the protocols care about.",
  ev="preclinical", evNote="The full protein reached early human trials; this fragment has no approved use and no set human dose.",
  protocol=[NOHUMAN, ("Animal studies","Loading then maintenance","Protocols front-load twice a week, then drop the frequency."),
            ("Legal status","Not approved","Banned in sport at all times. " + RESEARCH)],
  benefits=["Helps cells migrate to damaged tissue — the core of how it's thought to work.",
            "Grows blood vessels and remodels tissue in injury models.",
            "Commonly paired with BPC-157 because they work differently.",
            "Reduces scarring in animal heart studies."],
  sizes=[(10,"mg",1800000)], dose=2, unit="mg",
  storage=FRIDGE_LIGHT, cautions=["Banned in tested sport at all times.","No human safety data.", "Research use only."]),

dict(slug="wolverine", name="BPC-157 + TB-500 (Wolverine)", cat="Healing & Repair",
  what="The two best-known repair peptides in one pen. They're almost always used together, so this saves doing two injections.",
  cls="Combination repair peptide blend", half="Mixed — minutes to days", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="Daily in most protocols, driven by the BPC-157 half, which is the shorter-acting of the two.",
  when="Morning or evening", food="Either",
  timeNote="Usually run as a course of a few weeks around an injury, rather than taken indefinitely.",
  ev="preclinical", evNote="Neither part is approved, and the combination has never been trialled in people.",
  protocol=[NOHUMAN, ("Why combined","Different mechanisms","One protects and rebuilds tissue; the other helps cells reach the damage."),
            ("Legal status","Not approved","Banned in sport. " + RESEARCH)],
  benefits=["The two most-studied repair peptides in a single injection.",
            "They act differently, so the combination is complementary rather than doubled-up.",
            "Most often used around soft-tissue injuries."],
  sizes=[(20,"mg",2900000)], dose=2, unit="mg",
  storage=FRIDGE_LIGHT, cautions=["No human trials of the blend.","Banned in sport.","Research use only."]),

dict(slug="klow", name="KLOW (BPC + TB + GHK + KPV)", cat="Healing & Repair",
  what="A four-way repair blend: the two tendon peptides, plus a copper peptide for skin and collagen, plus an anti-inflammatory one.",
  cls="Four-peptide repair and anti-inflammatory blend", half="Mixed", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="Daily, usually as a defined course of a few weeks rather than ongoing.",
  when="Evening", food="Either",
  timeNote="Evening dosing is common so the repair signals overlap with sleep, when most tissue repair happens.",
  ev="preclinical", evNote="None of the four are approved for injection, and the blend has never been trialled.",
  protocol=[NOHUMAN, ("Why four","Repair, skin and inflammation","It covers tissue repair, collagen and the inflammatory side in one shot."),
            ("Legal status","Not approved", RESEARCH)],
  benefits=["Covers tissue repair, collagen building and inflammation in one injection.",
            "The copper peptide adds a skin and collagen angle the others don't have.",
            "KPV brings the anti-inflammatory side without steroids."],
  sizes=[(80,"mg",5800000)], dose=4, unit="mg",
  storage=FRIDGE_LIGHT, cautions=["Contains copper — not for anyone with a copper handling disorder.",
    "No human trials of the blend.","Research use only."]),

dict(slug="ghk-cu", name="GHK-Cu", cat="Healing & Repair",
  what="A copper-carrying peptide that your body makes less of as you age. It's the workhorse of serious skincare, and the human evidence is for putting it on your skin.",
  cls="Copper-binding tripeptide", half="Short in blood; lingers in skin", route="On the skin (human evidence) or injected (research)",
  cadence="daily", days=[1,1,1,1,1,1,1], perWeek=7,
  cadNote="Once or twice a day on the skin in the published human studies.",
  when="Evening, on clean skin", food="Not relevant — applied to skin",
  timeNote="Applied at night to cleansed skin, before heavier creams. Copper peptides break down in light, so night use suits them.",
  ev="regional", evNote="The human evidence is for skin creams, which are sold worldwide. Injecting it has no approved use and no set dose.",
  protocol=[("On the skin","Once or twice daily","The pattern used in cosmetic studies, at low concentrations."),
            ("Injected","Not set","No approved dose. How much copper you're taking on is the limiting factor."),
            ("Status","A cosmetic ingredient","Not approved as an injectable medicine.")],
  benefits=["Builds collagen and elastin — why it's in expensive skincare.",
            "Speeds wound healing and skin remodelling in dermatology studies.",
            "Calms inflammation and mops up oxidative damage.",
            "Studied for hair follicles as well as skin."],
  sizes=[(50,"mg",2600000),(100,"mg",5000000)], dose=2, unit="mg",
  storage="Keep it in the fridge and leave it in the box — copper peptides go off in light and change colour. Don't freeze.",
  cautions=["Copper builds up in the body. That's the main concern with injecting rather than applying it.",
    "Not for anyone with Wilson's disease or another copper disorder.","Injecting it is research use only."]),

dict(slug="ahk-cu", name="AHK-Cu", cat="Healing & Repair",
  what="GHK-Cu's cousin, studied mainly for hair rather than skin. Same copper-carrying idea, different peptide.",
  cls="Copper-binding tripeptide", half="Short", route="On the skin or injected (research)",
  cadence="daily", days=[1,1,1,1,1,1,1], perWeek=7,
  cadNote="Daily application in the hair studies that exist.",
  when="Evening, on clean scalp", food="Not relevant",
  timeNote="Applied at night. Like GHK-Cu, it's light-sensitive.",
  ev="preclinical", evNote="Mostly lab and small cosmetic studies. No approved medical use and no set dose.",
  protocol=[("Human dose","Not set","No approved use."),
            ("Studied as","A topical for hair","The published work is about hair follicles, not injection."),
            ("Status","A cosmetic ingredient", RESEARCH)],
  benefits=["Studied for hair follicle growth and thickness.",
            "Boosts collagen, like other copper peptides.",
            "Often combined with GHK-Cu in hair formulas."],
  sizes=[(100,"mg",2500000)], dose=2, unit="mg",
  storage="Fridge, in the box, away from light. Don't freeze.",
  cautions=["Contains copper — not for anyone with a copper handling disorder.","Very little human data."]),

dict(slug="ara-290", name="ARA-290", cat="Healing & Repair",
  what="A small peptide built from part of the EPO hormone, but with the blood-building part removed. It's studied for nerve pain rather than blood.",
  cls="Erythropoietin-derived peptide (non-haematopoietic)", half="Short — minutes", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,1,1], perWeek=7,
  cadNote="Daily in the trials, over courses of several weeks.",
  when="Any time of day", food="Either",
  timeNote="Trials used a consistent daily time. It clears fast, but its effect on nerves outlasts its presence in blood.",
  ev="trial", evNote="Not approved, but it has completed real human trials for small-fibre nerve damage in sarcoidosis and diabetes.",
  protocol=[("Trial dose","4 mg daily","The dose used in the published human trials."),
            ("Trial length","28 days typically","Run as a defined course rather than ongoing."),
            ("Status","Not approved","Trials showed promise for nerve pain; it hasn't reached approval.")],
  benefits=["Studied for small-fibre nerve damage and the pain that comes with it.",
            "Doesn't thicken the blood, unlike EPO itself — that part was deliberately removed.",
            "Calms inflammation in nerve tissue.",
            "Has actual human trial data behind it, which most of this category lacks."],
  sizes=[(10,"mg",2800000),(50,"mg",4100000)], dose=4, unit="mg",
  storage=FRIDGE, cautions=["Not an approved medicine.","Human data is limited to small trials."]),

dict(slug="kpv", name="KPV", cat="Healing & Repair",
  what="The last three amino acids of a natural hormone, and the part that calms inflammation. Small, simple, and studied mostly for the gut and skin.",
  cls="Alpha-MSH C-terminal tripeptide", half="Short", route="Under the skin or by mouth in studies",
  cadence="daily", days=[1,1,1,1,1,1,1], perWeek=7,
  cadNote="Daily in study protocols, usually as a short course while inflammation settles.",
  when="Any time of day", food="Either",
  timeNote="Taken by mouth in gut studies so it reaches the bowel directly; injected when the target is elsewhere.",
  ev="preclinical", evNote="Animal and lab data only. No approved use and no established human dose.",
  protocol=[NOHUMAN, ("Studied in","Colitis and skin models","Most of the work is on inflamed bowel and skin."),
            ("Status","Not approved", RESEARCH)],
  benefits=["Calms inflammation without the side effects of steroids, in animal models.",
            "Studied for inflammatory bowel conditions.",
            "Also studied for acne and eczema-type skin inflammation.",
            "Has antimicrobial activity in lab work."],
  sizes=[(10,"mg",2300000)], dose=0.5, unit="mg",
  storage=FRIDGE, cautions=["No human trials.","Research use only."]),

dict(slug="ll-37", name="LL-37", cat="Healing & Repair",
  what="Your body's own antibiotic peptide, part of the immune system's first line of defence against bacteria.",
  cls="Human cathelicidin antimicrobial peptide", half="Short", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="Daily in study protocols, as a short course rather than ongoing.",
  when="Any time of day", food="Either",
  timeNote="Used in short bursts in the literature rather than continuously.",
  ev="preclinical", evNote="Lab and animal data. No approved use and no set human dose.",
  protocol=[NOHUMAN, ("Studied for","Bacterial biofilms","It's studied against bacteria that resist normal antibiotics."),
            ("Status","Not approved", RESEARCH)],
  benefits=["Kills bacteria directly, including some that shrug off antibiotics.",
            "Breaks up biofilms — the protective layers bacteria build.",
            "Also involved in wound healing and immune signalling."],
  sizes=[(5,"mg",2700000)], dose=0.1, unit="mg",
  storage=FRIDGE, cautions=["Can irritate tissue and provoke inflammation at higher amounts.",
    "No human trials.","Research use only."]),

dict(slug="peg-mgf", name="Peg MGF", cat="Healing & Repair",
  what="A muscle growth factor that your body releases when muscle is damaged. The PEG part makes it last longer than the natural version.",
  cls="Pegylated mechano growth factor (IGF-1Ec splice variant)", half="Extended by pegylation", route="Under the skin",
  cadence="cycle", days=[1,0,1,0,1,0,0], perWeek=3,
  cadNote="A few times a week in study protocols, often after training rather than every day.",
  when="After training", food="Either",
  timeNote="Study protocols time it around muscle damage, since that's when the natural version is released.",
  ev="preclinical", evNote="Lab reagent. No approved use, no human trials, no set dose.",
  protocol=[NOHUMAN, ("Studied for","Muscle repair after damage","It's the signal muscle sends when it's been stressed."),
            ("Status","Not approved","Banned in sport. " + RESEARCH)],
  benefits=["Activates the satellite cells that repair and grow muscle.",
            "Lasts longer than natural MGF thanks to the PEG modification.",
            "Studied for muscle repair after injury."],
  sizes=[(2,"mg",2800000)], dose=0.2, unit="mg",
  storage=FRIDGE_LIGHT, cautions=["A growth signal — a real concern if any cancer is present.",
    "No human data. Banned in sport."]),

dict(slug="snap-8", name="SNAP-8", cat="Healing & Repair",
  what="A peptide used in anti-wrinkle creams. It softens the muscle contractions that cause expression lines — the same idea as Botox, far gentler and applied to the skin.",
  cls="Acetyl octapeptide-3", half="Not relevant — applied to skin", route="On the skin",
  cadence="daily", days=[1,1,1,1,1,1,1], perWeek=7,
  cadNote="Applied once or twice a day in cosmetic use.",
  when="Morning and evening, on clean skin", food="Not relevant",
  timeNote="Applied to cleansed skin, before heavier creams. Results build over weeks, not days.",
  ev="regional", evNote="A cosmetic ingredient sold worldwide in creams. Not a medicine, and not intended for injection.",
  protocol=[("In creams","Low percentage, twice daily","The way it's used in commercial cosmetics."),
            ("Injected","Not intended","This is a topical ingredient — it isn't an injectable."),
            ("Status","Cosmetic ingredient","Regulated as a cosmetic, not a drug.")],
  benefits=["Softens expression lines around the eyes and forehead.",
            "A topical alternative to injectables, without needles.",
            "Well tolerated on skin in cosmetic testing."],
  sizes=[(10,"mg",2500000)], dose=1, unit="mg",
  storage="Cool and dark. Fridge is fine. Don't freeze.",
  cautions=["Meant for skin, not injection.","Effects are subtle compared with injectables."]),
]
