# -*- coding: utf-8 -*-
"""Compound table, part 1 — categories 01-03. Prices in IDR from the price list."""

# Shared storage lines, so the wording stays consistent across the catalogue.
FRIDGE = "Keep it in the fridge, 2–8 °C. Don't freeze it. Keep it in its box, out of the light."
FRIDGE_LIGHT = "Keep it in the fridge, 2–8 °C, and leave it in its box — light damages it. Don't freeze it."

C1 = [
dict(slug="tirzepatide", name="Tirzepatide", cat="Weight Loss & GLP-1",
  what="A weekly shot that copies two gut hormones. It slows how fast your stomach empties and turns down appetite, so you eat less without white-knuckling it.",
  cls="Dual GIP / GLP-1 receptor agonist", half="About 5 days", route="Under the skin",
  cadence="weekly", days=[1,0,0,0,0,0,0], perWeek=1,
  cadNote="Once a week, same day every week. It stays in your body about five days, so a weekly rhythm keeps the level steady.",
  when="Any time of day", food="With or without food",
  timeNote="The day matters more than the hour. Pick a day that stays easy across work and travel, and keep it.",
  ev="label", evNote="Approved as Mounjaro and Zepbound in the US and Europe. The doses below are the ones on the official label.",
  protocol=[("Starting dose","2.5 mg once a week","A starter dose to let your stomach adjust. It isn't meant to be the dose you stay on."),
            ("After 4 weeks","5 mg once a week","The first real working dose."),
            ("Going up","+2.5 mg at a time","Wait at least 4 weeks at each step before going up again."),
            ("Most you should take","15 mg once a week","The ceiling on the label."),
            ("Missed a dose","Within 4 days, take it","Longer than that, skip it and go back to your normal day.")],
  benefits=["Steady, well-documented weight loss — the trial data runs to 72 weeks.",
            "Better blood sugar control, which is what it was first approved for.",
            "Less food noise: the constant background thinking about eating quietens down.",
            "Blood pressure and cholesterol tended to improve too, alongside the weight."],
  sizes=[(10,"mg",2200000),(30,"mg",3500000),(40,"mg",4000000)], dose=2.5, unit="mg",
  storage="Keep it in the fridge, 2–8 °C. Don't freeze it. Don't use it if the liquid looks cloudy or has changed colour.",
  cautions=["Don't use it if you or your family have had medullary thyroid cancer or MEN 2.",
            "Nausea is the usual limit. Going up too fast is what makes people feel awful — slow down instead of pushing through.",
            "A prescription medicine in most countries."]),

dict(slug="retatrutide", name="Retatrutide", cat="Weight Loss & GLP-1",
  what="A weekly shot aimed at three appetite and metabolism switches instead of two. It's the newest of this family and, so far, the strongest in trials.",
  cls="Triple GIP / GLP-1 / glucagon receptor agonist", half="About 6 days", route="Under the skin",
  cadence="weekly", days=[1,0,0,0,0,0,0], perWeek=1,
  cadNote="Retatrutide stays in your body about six days. That long tail is why the schedule is anchored to a weekly total rather than a daily one — how you split that total across the week is the choice above.",
  when="Any time of day", food="With or without food",
  timeNote="Stomach side effects tend to be worst in the two days after a shot, which is worth planning your week around.",
  ev="trial", evNote="Not approved anywhere yet — it's still in trials. The numbers below are what the trials used, not an official dose.",
  protocol=[("Trial range","1–12 mg once a week","The trials tested across this range, building up slowly."),
            ("Building up","In steps, over months","Trials moved up roughly every 4 weeks from a low start."),
            ("Official dose","None yet","No regulator has set one. Outside a trial, there is no agreed protocol.")],
  benefits=["The largest weight loss reported so far in this class of trial.",
            "Works on three pathways at once, including one the others don't touch.",
            "Also studied for shifting fat stored in the liver."],
  regimens=[
    dict(id="weekly", label="Once a week", sub="2 mg in one go", dose=2, perWeek=1, days=[1,0,0,0,0,0,0],
         note="What the trials did — one injection a week. Retatrutide stays in your body about six days, so a single weekly dose holds a steady level on its own."),
    dict(id="split", label="Twice a week", sub="1 mg each time", dose=1, perWeek=2, days=[1,0,0,1,0,0,0],
         note="The same amount across the week, split into two injections three or four days apart. Each dose peaks lower, which some people find easier on the stomach. The trials did not test this — it is a practical adjustment, not a tested protocol, so the weekly total is what stays anchored to the trial range."),
  ],
  sizes=[(10,"mg",2700000),(20,"mg",3600000),(30,"mg",4900000),(40,"mg",6400000),(60,"mg",8500000)], dose=2, unit="mg",
  storage="Keep it in the fridge, 2–8 °C. Don't freeze it — freezing and thawing wrecks it. Keep it out of the light.",
  cautions=["Still experimental. The full picture on long-term safety isn't in yet.",
            "Stomach upset is the main thing that limits the dose in trials.",
            "Not a licensed medicine."]),

dict(slug="cagrilintide", name="Cagrilintide", cat="Weight Loss & GLP-1",
  what="A weekly shot that copies amylin, the hormone that tells you you've had enough. It's usually studied alongside a GLP-1 rather than on its own.",
  cls="Long-acting amylin analogue", half="About 7–8 days", route="Under the skin",
  cadence="weekly", days=[1,0,0,0,0,0,0], perWeek=1,
  cadNote="Once a week — it lasts long enough that a weekly rhythm holds the level steady.",
  when="Any time of day", food="With or without food",
  timeNote="Same principle as the others: pick a day and keep it.",
  ev="trial", evNote="Not approved. It's in late-stage trials, mostly paired with semaglutide as CagriSema.",
  protocol=[("Trial range","0.3–4.5 mg once a week","Doses tested in the published trials."),
            ("Building up","In steps over several weeks","Trials escalated gradually, as with the GLP-1s."),
            ("Official dose","None yet","No approval, so no agreed dose.")],
  benefits=["Works on fullness through a different hormone than the GLP-1 drugs.",
            "Because the pathway differs, it adds to a GLP-1 rather than overlapping with it.",
            "Studied for holding onto weight loss rather than just causing it."],
  sizes=[(10,"mg",2700000)], dose=1, unit="mg",
  storage=FRIDGE,
  cautions=["Experimental — no approved use.","Nausea, as with the rest of this family."]),

dict(slug="aod-9604", name="AOD-9604", cat="Weight Loss & GLP-1",
  what="A small fragment of growth hormone, kept only for the part linked to fat breakdown. The idea was fat loss without the growth-hormone side effects.",
  cls="Growth hormone fragment (hGH 176-191)", half="Short — under an hour", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,1,1], perWeek=7,
  cadNote="Daily in study protocols, because it clears the body quickly.",
  when="Morning, before eating", food="Fasted — before breakfast",
  timeNote="Study protocols used it fasted in the morning, on the theory that food blunts the fat-burning effect.",
  ev="trial", evNote="It went through human obesity trials and did not beat placebo on weight. It is not approved as a medicine.",
  protocol=[("Trial dose","1 mg daily","The dose used in the human obesity trials."),
            ("Result","Did not beat placebo","Worth knowing before spending on it — the weight-loss trials were negative."),
            ("Approved use","None","Sold in some places as a food ingredient, not as a medicine.")],
  benefits=["Doesn't raise blood sugar or IGF-1 the way full growth hormone does.",
            "Still studied for cartilage and joint repair, where the early signals were better than for fat loss.",
            "Well tolerated in the trials that were run."],
  sizes=[(5,"mg",2700000)], dose=0.3, unit="mg",
  storage=FRIDGE,
  cautions=["The human weight-loss trials were negative — be sceptical of fat-loss claims.",
            "No approved medical use."]),
]
