# -*- coding: utf-8 -*-
"""Part 2 — 02 Growth Hormone, 03 Healing & Repair."""
from data1 import FRIDGE, FRIDGE_LIGHT

NIGHT = "Growth hormone comes out in pulses, mostly while you sleep. Taking it at night works with that rhythm instead of against it. A big carby meal beforehand blunts the pulse."

C2 = [
dict(slug="cjc-ipamorelin", name="CJC-1295 + Ipamorelin", cat="Growth Hormone",
  what="Two peptides that nudge your own body to release more growth hormone, from two different angles. It's the most common pairing in this category.",
  cls="GHRH analogue + selective ghrelin receptor agonist", half="30 minutes and 2 hours", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="Daily, usually before bed, because both parts clear quickly. Five days on and two off is common in practice, though it isn't from trial data.",
  when="Before sleep", food="Empty stomach — at least 2 hours after eating", timeNote=NIGHT,
  ev="preclinical", evNote="Not approved as a combination. Ipamorelin was dropped during drug development, and CJC-1295 without DAC has no approved use.",
  protocol=[("Human dose","Not set","There's no approved dose for this combination."),
            ("Why at night","Growth hormone peaks in sleep","That's the basis for evening timing in the studies that exist."),
            ("Why fasted","Food blunts the response","High blood sugar suppresses the release you're trying to trigger.")],
  benefits=["Prompts your own growth hormone rather than injecting the hormone itself.",
            "Ipamorelin is the clean one — it doesn't push up cortisol or prolactin the way older versions did.",
            "Studied for recovery, deeper sleep, and body composition."],
  sizes=[(10,"mg",2700000),(20,"mg",3800000)], dose=0.2, unit="mg",
  storage=FRIDGE_LIGHT,
  cautions=["Growth hormone signalling can make you less sensitive to insulin.","Banned in tested sport."]),

dict(slug="cjc-1295-dac", name="CJC-1295 (With DAC)", cat="Growth Hormone",
  what="The long-acting version of CJC-1295. The DAC part makes it stick to a blood protein so it lasts days instead of minutes — so you inject it weekly, not nightly.",
  cls="GHRH analogue with drug affinity complex", half="About 6–8 days", route="Under the skin",
  cadence="weekly", days=[1,0,0,0,0,0,0], perWeek=1,
  cadNote="Once or twice a week. The DAC modification is exactly what buys the longer gap between shots.",
  when="Any time of day", food="Either", timeNote="Because it lasts days, the timing of each shot matters much less than with the short-acting version.",
  ev="preclinical", evNote="No approved use. Development stopped after a safety problem in an early trial.",
  protocol=[("Human dose","Not set","No approved dose."),
            ("Why weekly","It lasts about a week","The long half-life is the whole point of the DAC version."),
            ("Development","Stopped","An early trial was halted; it was never approved.")],
  benefits=["Raises the baseline of growth hormone rather than making single pulses.",
            "Far fewer injections than the short-acting version."],
  sizes=[(5,"mg",2900000)], dose=1, unit="mg",
  storage=FRIDGE_LIGHT,
  cautions=["Development was stopped after a safety signal — that matters.",
            "A steady raised level is less like normal body rhythm than a nightly pulse.","Banned in tested sport."]),

dict(slug="ipamorelin", name="Ipamorelin", cat="Growth Hormone",
  what="The gentlest of the growth hormone releasers. It triggers a clean pulse without dragging cortisol, prolactin or hunger up with it.",
  cls="Selective ghrelin receptor agonist", half="About 2 hours", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="Daily, usually at night. Short-acting, so it's about creating a pulse rather than a steady level.",
  when="Before sleep", food="Empty stomach — at least 2 hours after eating", timeNote=NIGHT,
  ev="preclinical", evNote="Was tested in humans for gut recovery after surgery, missed its target, and development stopped. No approved use.",
  protocol=[("Human dose","Not set","No approved dose."),
            ("Trials","Stopped after missing endpoints","It was tested for bowel recovery after surgery and didn't work well enough."),
            ("Selectivity","Its main selling point","Unlike older versions, it doesn't raise cortisol or prolactin much.")],
  benefits=["The cleanest profile in this group — minimal knock-on hormone effects.",
            "Doesn't cause the strong hunger that some older releasers do.",
            "Often paired with a GHRH peptide because the two work differently."],
  sizes=[(10,"mg",2500000)], dose=0.2, unit="mg",
  storage=FRIDGE_LIGHT,
  cautions=["Failed its human trials for the use it was developed for.","Banned in tested sport."]),

dict(slug="tesamorelin", name="Tesamorelin", cat="Growth Hormone",
  what="A daily shot that raises your own growth hormone. It's the one with real approval behind it, specifically for shifting deep belly fat.",
  cls="Stabilised GHRH analogue", half="26–38 minutes", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,1,1], perWeek=7,
  cadNote="Once a day. It's out of your system in under an hour, so a weekly version simply wouldn't work.",
  when="Before bed", food="Empty stomach — 2 hours after eating", timeNote=NIGHT,
  ev="label", evNote="Approved by the FDA as Egrifta for belly fat in people with HIV. The dose below is the official one.",
  protocol=[("Official dose","2 mg once a day","Under the skin, into the belly, moving the spot each time."),
            ("Timing","Same time daily","Usually at night, in line with your natural growth hormone rhythm."),
            ("Review","At 6 months","The label says to check whether it's still worth continuing.")],
  benefits=["Reduces visceral fat — the deep belly fat around organs. That's the approved use.",
            "Prompts your own growth hormone instead of replacing it.",
            "Also studied for liver fat and triglycerides."],
  sizes=[(10,"mg",2300000),(20,"mg",3300000)], dose=2, unit="mg",
  storage="Keep it in the fridge, 2–8 °C. Don't freeze it. Out of the light.",
  cautions=["Not for use in active cancer, or in pregnancy.",
            "Keep an eye on blood sugar — growth hormone can reduce insulin sensitivity.",
            "A prescription medicine."]),

dict(slug="ipamorelin-tesamorelin", name="Ipamorelin + Tesamorelin", cat="Growth Hormone",
  what="Tesamorelin's approved belly-fat effect paired with Ipamorelin's clean pulse, in one pen. Two different triggers on the same system.",
  cls="GHRH analogue + selective ghrelin receptor agonist", half="30 minutes and 2 hours", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="Daily, at night. Both parts are short-acting, so the point is a nightly pulse.",
  when="Before sleep", food="Empty stomach — at least 2 hours after eating", timeNote=NIGHT,
  ev="preclinical", evNote="Tesamorelin on its own is approved; this combination is not, and hasn't been trialled as a pair.",
  protocol=[("Human dose","Not set for the pair","Tesamorelin alone has an approved dose of 2 mg daily; the combination has none."),
            ("Why combine","Two different triggers","One acts on the releasing hormone, the other on the ghrelin receptor."),
            ("Why at night","Growth hormone peaks in sleep","Same reasoning as the other pairings.")],
  benefits=["Combines the one approved compound in this group with the cleanest one.",
            "Two pathways at once, which tends to produce a bigger pulse than either alone.",
            "One injection rather than two."],
  sizes=[(18,"mg",4500000)], dose=0.5, unit="mg",
  storage=FRIDGE_LIGHT,
  cautions=["The combination itself hasn't been trialled.","Watch blood sugar.","Banned in tested sport."]),

dict(slug="sermorelin", name="Sermorelin", cat="Growth Hormone",
  what="The original growth-hormone releaser. It was an approved medicine for years, used to test whether a child's pituitary was working.",
  cls="GHRH (1-29) analogue", half="About 10–20 minutes", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,1,1], perWeek=7,
  cadNote="Daily at night. Very short-acting — it's gone within the hour.",
  when="Before sleep", food="Empty stomach — 2 hours after eating", timeNote=NIGHT,
  ev="label", evNote="Was FDA-approved as Geref, then withdrawn from the market in 2008 for business reasons rather than safety. Still made by compounding pharmacies in some countries.",
  protocol=[("Old official dose","0.03 mg per kg daily","The dose from the label when it was on the market."),
            ("Status","Withdrawn from market","Pulled in 2008 — a commercial decision, not a safety one."),
            ("Now","Compounded in some countries","Availability depends entirely on where you are.")],
  benefits=["The longest track record of any peptide in this group, with a real approval history.",
            "Works with your own pituitary, so the body's feedback loops stay in charge.",
            "Well-characterised safety profile from its years on the market."],
  sizes=[(10,"mg",3100000)], dose=0.3, unit="mg",
  storage=FRIDGE_LIGHT,
  cautions=["No longer a marketed medicine in most places.","Banned in tested sport."]),

dict(slug="hgh-191aa", name="HGH 191AA (Somatropin)", cat="Growth Hormone",
  what="Growth hormone itself, made to match the human sequence exactly. Not a trigger for your own supply — this is the hormone.",
  cls="Recombinant human growth hormone", half="About 3–5 hours", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,1,1], perWeek=7,
  cadNote="Once a day, usually in the evening. Some protocols split it across the day.",
  when="Evening", food="Either", timeNote="Evening dosing lines up roughly with the body's own night-time release.",
  ev="label", evNote="Approved worldwide as a medicine for growth hormone deficiency and several other conditions. Doses are set by a doctor for the specific condition.",
  protocol=[("Adult deficiency","0.2–1 IU daily, typically","Real doses are set individually and adjusted from blood tests."),
            ("Adjusted by","IGF-1 blood levels","This is monitored by a doctor — it is not a set-and-forget dose."),
            ("Status","Prescription only","Tightly controlled in most countries.")],
  benefits=["The real hormone, with decades of medical use behind it.",
            "Approved for a list of genuine medical conditions.",
            "Effects on muscle, fat and recovery are well documented."],
  sizes=[(36,"IU",2800000),(40,"IU",3000000)], dose=2, unit="IU",
  storage="Keep it in the fridge, 2–8 °C. Never freeze it. Keep it out of the light.",
  cautions=["Prescription only, and a controlled substance in several countries.",
            "Can raise blood sugar, cause fluid retention and joint aches, and trigger carpal tunnel.",
            "Not for use with active cancer. Banned in tested sport."]),

dict(slug="igf-1-lr3", name="IGF-1 LR3", cat="Growth Hormone",
  what="A modified version of the growth factor that growth hormone actually works through. The changes make it last far longer than the natural one.",
  cls="Long-acting insulin-like growth factor 1 analogue", half="About 20–30 hours", route="Under the skin",
  cadence="daily", days=[1,1,1,1,1,0,0], perWeek=5,
  cadNote="Daily in study protocols. It lasts much longer than natural IGF-1, which is the point of the modification.",
  when="Morning or after training", food="Either — but it affects blood sugar",
  timeNote="It acts a bit like insulin and can drop blood sugar, so study protocols avoid taking it on a completely empty stomach.",
  ev="preclinical", evNote="A lab reagent, not a medicine. There is no approved human use and no set dose.",
  protocol=[("Human dose","Not set","No approved use in people."),
            ("Blood sugar","The main practical issue","It can lower blood sugar noticeably."),
            ("Status","Research reagent","Sold for laboratory work. Banned in sport.")],
  benefits=["Acts directly on the growth pathway rather than going through the pituitary.",
            "Much longer-lasting than natural IGF-1.",
            "Studied for muscle growth and nerve repair."],
  sizes=[(1,"mg",3800000)], dose=0.05, unit="mg",
  storage="Keep it in the fridge, 2–8 °C. Don't freeze it. It's fragile — handle gently and keep it dark.",
  cautions=["Can drop blood sugar — the most immediate risk here.",
            "It's a growth signal, which is a real concern if any cancer is present.",
            "No human safety data at all. Banned in sport."]),
]
